---
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - run: sudo apt-get install -y dbus dbus-x11
      - run: python -m pip install --upgrade tox
      - # Fake a TTY
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: "python -m tox -e py"
